### ISSUE TITLE
Hey, Bud

### ISSUE THREAD

**Issue by SecretKyro** [Lightning-X/Aera#1]
Hey, Vali I love to see the work but I also don't think you understand the point of simplicity I highly doubt anyone with little c++ knowledge would understand this and also it has quite a bit of useless features added maybe work on it being more barebones and also make sure to add more comments to make it easier for other people to understand your work but other than that good job keep up the work 👍

**Comment by Vali0004** [comment]
It was never meant to be used, more of a documentation.
Please do not make needless issues, instead contact me personally.
